import csv
import time
from dotenv import load_dotenv

from services.gmail.gmail import smtp_send_email

load_dotenv()

def mock_thread(product, messages) -> None:

    pause_seconds = 0.25

    subject = f"Grow Your Business With {product}"

    # send the first message through
    root_msg_id = smtp_send_email(subject, messages[0])
    time.sleep(pause_seconds)

    # and then thread the reploies
    for body in messages[1:]:
        smtp_send_email(f"Re: {subject}", body, reply_to=root_msg_id, references=root_msg_id)
        time.sleep(pause_seconds)


def mock_gmail_data() -> None:
    ## sales mock data generated by chatgpt using random data sets with different google products as examples
    with open("sales_mock_data.csv", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        group_messages = []
        threads_sent = 0

        for r in reader:
            product = r["product_name"].strip()
            message = r["message"].strip()

            group_messages.append(message)

            # group into group of 4 (every email thread is 4 for simplicity)
            if len(group_messages) == 4:
                mock_thread(product, group_messages)
                threads_sent += 1
                group_messages = []

                print(f"Finished mocking a thread for {product} ({threads_sent} of 15)")

                # just hard coding 15 threads for now
                if threads_sent >= 15:
                    break

if __name__ == "__main__":
    mock_gmail_data()
