import csv
import time
from dotenv import load_dotenv

from services.gmail import smtp_send_email
from services.gmail import retrieve_email

load_dotenv()

def mock_thread(product, messages):

    pause_seconds = 0.25

    subject = f"Grow Your Business With {product}"

    # send the first message through
    prev_message_id = smtp_send_email(subject, messages[0])
    time.sleep(pause_seconds)

    references = prev_message_id

    # and then thread the reploies
    for body in messages[1:]:
        prev_message_id = smtp_send_email(f"Re: {subject}", body, reply_to=prev_message_id, references=references)
        references = prev_message_id + ' ' + references
        time.sleep(pause_seconds)


def mock_gmail_data(number_to_mock):
    ## sales mock data generated by chatgpt using random data sets with different google products as examples
    with open("data/email_threads.csv", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        group_messages = []
        threads_sent = 0

        for r in reader:
            product = r["product_name"].strip()
            message = r["message"].strip()

            group_messages.append(message)

            # group into group of 4 (every email thread is 4 for simplicity)
            if len(group_messages) == 4:
                mock_thread(product, group_messages)
                threads_sent += 1
                group_messages = []

                print(f"Finished mocking a thread for {product} ({threads_sent} of {number_to_mock})")

                if threads_sent >= number_to_mock:
                    break

def sync_gmail_data():
    retrieve_email()
    

if __name__ == "__main__":
    #mock_gmail_data(1)
    sync_gmail_data();

